CREATE TABLE `occurrences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`account` varchar(20) NOT NULL,
	`eventCode` varchar(10) NOT NULL,
	`qualifier` varchar(2),
	`partition` varchar(5),
	`zoneUser` varchar(10),
	`description` text,
	`priority` varchar(20),
	`brand` varchar(50),
	`clientId` int,
	`clientName` varchar(255),
	`systemId` int,
	`partnerCompanyId` int,
	`operatorId` int,
	`operatorName` varchar(255),
	`status` enum('finalized','cancelled','escalated') NOT NULL DEFAULT 'finalized',
	`observations` text,
	`logs` text,
	`attendingTimeMs` int,
	`sendEmail` boolean DEFAULT false,
	`sendPush` boolean DEFAULT false,
	`eventReceivedAt` timestamp,
	`startedAt` timestamp,
	`finalizedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `occurrences_id` PRIMARY KEY(`id`)
);
